### ISSUE TITLE
[Install] pdf-visualizer test fails

### ISSUE THREAD

**Issue by jibe-b** [ckorzen/icecite#4]
Running ```mvin install -e -X```, skipping succesful tests

```-------------------------------------------------------
 T E S T S
-------------------------------------------------------
[DEBUG] boot classpath:  /home/user/.m2/repository/org/apache/maven/surefire/surefire-booter/2.17/surefire-booter-2.17.jar  /home/user/.m2/repository/org/apache/maven/surefire/surefire-api/2.17/surefire-api-2.17.jar  /home/user/icecite/pdf-visualizer/target/test-classes  /home/user/icecite/pdf-visualizer/target/classes  /home/user/.m2/repository/org/apache/pdfbox/pdfbox/2.0.0/pdfbox-2.0.0.jar  /home/user/.m2/repository/org/apache/pdfbox/fontbox/2.0.0/fontbox-2.0.0.jar  /home/user/.m2/repository/commons-logging/commons-logging/1.2/commons-logging-1.2.jar  /home/user/.m2/repository/commons-cli/commons-cli/1.3.1/commons-cli-1.3.1.jar  /home/user/icecite/pdf-models/target/pdf-models-0.0.1-SNAPSHOT.jar  /home/user/.m2/repository/org/json/json/20151123/json-20151123.jar  /home/user/icecite/commons/target/commons-0.0.1-SNAPSHOT.jar  /home/user/.m2/repository/org/mockito/mockito-core/1.9.5/mockito-core-1.9.5.jar  /home/user/.m2/repository/org/objenesis/objenesis/1.0/objenesis-1.0.jar  /home/user/.m2/repository/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar  /home/user/.m2/repository/log4j/log4j/1.2.17/log4j-1.2.17.jar  /home/user/.m2/repository/junit/junit/4.11/junit-4.11.jar  /home/user/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar  /home/user/.m2/repository/com/google/inject/guice/3.0/guice-3.0.jar  /home/user/.m2/repository/javax/inject/javax.inject/1/javax.inject-1.jar  /home/user/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar  /home/user/.m2/repository/org/apache/maven/surefire/surefire-junit4/2.17/surefire-junit4-2.17.jar
[DEBUG] boot(compact) classpath:  surefire-booter-2.17.jar  surefire-api-2.17.jar  test-classes  classes  pdfbox-2.0.0.jar  fontbox-2.0.0.jar  commons-logging-1.2.jar  commons-cli-1.3.1.jar  pdf-models-0.0.1-SNAPSHOT.jar  json-20151123.jar  commons-0.0.1-SNAPSHOT.jar  mockito-core-1.9.5.jar  objenesis-1.0.jar  trove4j-3.0.3.jar  log4j-1.2.17.jar  junit-4.11.jar  hamcrest-core-1.3.jar  guice-3.0.jar  javax.inject-1.jar  aopalliance-1.0.jar  surefire-junit4-2.17.jar
Forking command line: /bin/sh -c cd /home/user/icecite/pdf-visualizer && /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -jar /home/user/icecite/pdf-visualizer/target/surefire/surefirebooter7223776142380328252.jar /home/user/icecite/pdf-visualizer/target/surefire/surefire3595207985384827380tmp /home/user/icecite/pdf-visualizer/target/surefire/surefire_23644691768135619115tmp
Running drawer.pdfbox.PdfBoxDrawerTest
src/test/resources/PdfBoxVisualizerTest/groundtruth/groundtruth-1.pdf
src/test/resources/PdfBoxVisualizerTest/output/output-1.pdf
true
Tests run: 8, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.319 sec <<< FAILURE! - in drawer.pdfbox.PdfBoxDrawerTest
testConstructorWithNull(drawer.pdfbox.PdfBoxDrawerTest)  Time elapsed: 0.005 sec  <<< ERROR!
java.lang.Exception: Unexpected exception, expected<java.lang.NullPointerException> but was<java.lang.IllegalArgumentException>
at drawer.pdfbox.PdfBoxDrawer.<init>(PdfBoxDrawer.java:90)
at drawer.pdfbox.PdfBoxDrawer.<init>(PdfBoxDrawer.java:80)
at drawer.pdfbox.PdfBoxDrawerTest.testConstructorWithNull(PdfBoxDrawerTest.java:71)


Results :

Tests in error: 
  PdfBoxDrawerTest.testConstructorWithNull »  Unexpected exception, expected<jav...

Tests run: 8, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] commons ............................................ SUCCESS [ 20.209 s]
[INFO] pdf-parent ......................................... SUCCESS [  0.606 s]
[INFO] pdf-models ......................................... SUCCESS [ 14.005 s]
[INFO] pdf-serializer ..................................... SUCCESS [ 13.753 s]
[INFO] pdf-statistics ..................................... SUCCESS [ 13.340 s]
[INFO] pdf-visualizer ..................................... FAILURE [  2.530 s]
[INFO] pdf-parser ......................................... SKIPPED
[INFO] pdf-parser-extended ................................ SKIPPED
[INFO] pdf-analyzer ....................................... SKIPPED
[INFO] pdf-revisor ........................................ SKIPPED
[INFO] pdf-cli ............................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:04 min
[INFO] Finished at: 2017-07-07T18:27:54+02:00
[INFO] Final Memory: 42M/891M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test (default-test) on project pdf-visualizer: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/user/icecite/pdf-visualizer/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test (default-test) on project pdf-visualizer: There are test failures.

Please refer to /home/user/icecite/pdf-visualizer/target/surefire-reports for the individual test results.
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: There are test failures.

Please refer to /home/user/icecite/pdf-visualizer/target/surefire-reports for the individual test results.
at org.apache.maven.plugin.surefire.SurefireHelper.reportExecution(SurefireHelper.java:82)
at org.apache.maven.plugin.surefire.SurefirePlugin.handleSummary(SurefirePlugin.java:195)
at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:861)
at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:729)
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
... 20 more
```

and /home/user/icecite/pdf-visualizer/target/surefire-reports/drawer.pdfbox.PdfBoxDrawerTest.txt

contains 

```-------------------------------------------------------------------------------
Test set: drawer.pdfbox.PdfBoxDrawerTest
-------------------------------------------------------------------------------
Tests run: 8, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.319 sec <<< FAILURE! - in drawer.pdfbox.PdfBoxDrawerTest
testConstructorWithNull(drawer.pdfbox.PdfBoxDrawerTest)  Time elapsed: 0.005 sec  <<< ERROR!
java.lang.Exception: Unexpected exception, expected<java.lang.NullPointerException> but was<java.lang.IllegalArgumentException>
        at drawer.pdfbox.PdfBoxDrawer.<init>(PdfBoxDrawer.java:90)
        at drawer.pdfbox.PdfBoxDrawer.<init>(PdfBoxDrawer.java:80)
        at drawer.pdfbox.PdfBoxDrawerTest.testConstructorWithNull(PdfBoxDrawerTest.java:71)
```

**Comment by jibe-b** [comment]
This seems to be an illegal exception error.

The java setup on my machine:

```
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-0ubuntu1.16.04.2-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode
```
